dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'

dotenv: .env

networks:
  default: development
  arbitrum-sepolia:
    host: ${WEB3_PROVIDER}
    chainid: 421614
